# Generated by Django 5.2.8 on 2025-12-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether the user has two-factor authentication enabled', verbose_name='two-factor enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('none', 'None'), ('email', 'Email')], default='none', help_text='The method used for two-factor authentication', max_length=20, verbose_name='two-factor method'),
        ),
    ]
