# Generated by Django 6.0.5 on 2026-05-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_businessinformation_follower_count_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
