# Generated by Django 5.2.8 on 2026-01-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_two_factor_enabled_user_two_factor_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text="User's unique username (can be updated later)", max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
