# Generated by Django 5.2.8 on 2026-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_step_login',
            field=models.BooleanField(default=False, help_text='Designates whether the user has two-step login on or off', verbose_name='two_step_login'),
        ),
    ]
