# Generated by Django 5.2.8 on 2026-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_two_step_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_chatbot_model',
            field=models.CharField(default='malik', help_text="User's default chatbot model", max_length=50),
        ),
    ]
