# Generated by Django 6.0.5 on 2026-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_businessinformation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='fuel_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='vehicle_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
