# Generated by Django 6.0.5 on 2026-09-07 06:06

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_businessinformation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='dealership_license_document',
            field=models.FileField(upload_to='licenses/', validators=[users.validators.validate_license_document]),
        ),
    ]
