# Generated by Django 5.2.8 on 2026-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_default_chatbot_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_chatbot_model',
            field=models.CharField(choices=[('malik', 'Malik Nadir'), ('maya', 'Maya Umani')], default='malik', help_text="User's default chatbot model", max_length=50),
        ),
    ]
