# Generated by Django 6.0.5 on 2026-06-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userpreference_budget_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_covers/'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='dealership_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='dealership_license_document',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='dealership_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='dealership_logo',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_logos/'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
