# Generated by Django 6.0.5 on 2026-09-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_businessinformation_dealership_license_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='specialization',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='vehicle_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
