# Generated by Django 6.0.5 on 2026-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_businessinformation_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='rejected_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
