# Generated by Django 5.2.8 on 2026-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_default_chatbot_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_chatbot_model',
            field=models.CharField(choices=[('malik', 'Malik Nadir'), ('maya', 'Maya Umani'), ('hiro', 'Hiro Lin')], default='malik', help_text="User's default chatbot model", max_length=50),
        ),
    ]
