# Generated by Django 5.2.8 on 2026-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_default_chatbot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice_mood',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('energetic', 'Energetic'), ('wise', 'Wise')], default='friendly', help_text="User's preferred voice mood for chatbot", max_length=20),
        ),
    ]
