# Generated by Django 6.0.5 on 2026-07-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='condition_prefs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='transmission_prefs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
