# Generated by Django 6.0.5 on 2026-07-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userpreference_condition_prefs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='fuel_preference',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='fuel_prefs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
