# Generated by Django 6.0.5 on 2026-09-07 10:56

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_fuel_preference_to_fuel_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='dealership_license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/', validators=[users.validators.validate_license_document]),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='specialization',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
