"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Read environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Hosts this site may be served under. Comma-separated in the environment, e.g.
#   DJANGO_ALLOWED_HOSTS=api.example.com,www.api.example.com,web,localhost
# "web" and "ws" are the internal Docker service names, needed so the
# car-video-agent's webhook call (which uses http://web:8000/...) is accepted.
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Origins allowed to send authenticated POST/PUT/DELETE to the admin and any
# session-authenticated view. Must include the scheme, e.g. https://api.example.com
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])

# Cross-origin browser access (the Flutter mobile app does not need this; a
# web dashboard does). Empty by default, which sends no CORS headers at all.
CORS_ALLOWED_ORIGINS = env.list('DJANGO_CORS_ALLOWED_ORIGINS', default=[])
CORS_ALLOW_CREDENTIALS = env.bool('DJANGO_CORS_ALLOW_CREDENTIALS', default=False)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders',
    'users',
    'vehicles',
    'messaging',
    'subscriptions',
]

AUTH_USER_MODEL = 'users.User'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware must sit as high as possible, and above CommonMiddleware,
    # so preflight responses still get the CORS headers.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.UpdateLastActiveMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Channel Layer for WebSockets.
#
# In production the HTTP workers (gunicorn) and the WebSocket worker (daphne)
# are SEPARATE processes. messaging/views.py pushes to the channel layer from
# an ordinary HTTP request, so an in-memory layer would silently deliver
# nothing. Redis is therefore required whenever REDIS_URL is set, and the
# in-memory layer stays only as a zero-dependency local-development fallback.
REDIS_URL = env('REDIS_URL', default='')

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        },
    }
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL drives this, e.g.
#   postgres://nory:password@db:5432/nory
# CONN_MAX_AGE keeps connections open between requests instead of opening a new
# PostgreSQL connection on every single API call.
DATABASES = {
    'default': env.db(),
}
DATABASES['default']['CONN_MAX_AGE'] = env.int('DJANGO_CONN_MAX_AGE', default=60)
DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# `collectstatic` copies the admin + django-unfold assets here, and nginx
# serves this directory directly. Django itself never serves static in prod.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_TITLE": "Auto Marketplace Admin",
    "SITE_HEADER": "Auto Marketplace",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Navigation",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                    {
                        "title": "Verification Requests",
                        "icon": "verified_user",
                        "link": "/admin/users/businessinformation/?verification_status__exact=pending",
                        "badge": "Pending",
                    },
                ],
            },
        ],
    },
}

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# In-App Purchase Settings
# Apple
APPLE_ISSUER_ID = env('APPLE_ISSUER_ID', default='')
APPLE_KEY_ID = env('APPLE_KEY_ID', default='')
APPLE_PRIVATE_KEY = env('APPLE_PRIVATE_KEY', default='').replace('\\n', '\n')
APPLE_BUNDLE_ID = env('APPLE_BUNDLE_ID', default='com.yourapp.bundle')
APPLE_ENVIRONMENT = env('APPLE_ENVIRONMENT', default='sandbox') # 'sandbox' or 'production'

# Google
GOOGLE_PLAY_PACKAGE_NAME = env('GOOGLE_PLAY_PACKAGE_NAME', default='com.yourapp.package')
GOOGLE_SERVICE_ACCOUNT_JSON = env('GOOGLE_SERVICE_ACCOUNT_JSON', default='') # Path to JSON key file

# AI Video Generation (external car-video-agent FastAPI service)
# Base URL of that service, e.g. http://127.0.0.1:8000 locally or an internal
# address in production. Django POSTs jobs to f"{AI_VIDEO_SERVICE_URL}/generate".
AI_VIDEO_SERVICE_URL = env('AI_VIDEO_SERVICE_URL', default='')
# Shared secret the webhook call must include as ?token=... . Set the
# car-video-agent's BACKEND_WEBHOOK_URL to:
#   https://<this-domain>/api/vehicles/ai-video/webhook/?token=<this-value>
# Left blank by default, which makes the webhook reject every request (fail closed).
AI_VIDEO_WEBHOOK_TOKEN = env('AI_VIDEO_WEBHOOK_TOKEN', default='')


# ---------------------------------------------------------------------------
# Firebase Admin SDK
# ---------------------------------------------------------------------------
# users/utils.py:initialize_firebase() reads this. It is a PATH to the service
# account JSON file, which is mounted read-only into the container at
# /run/secrets/firebase.json (see docker-compose.yml). Never commit the file.
FIREBASE_CREDENTIALS_PATH = env('FIREBASE_CREDENTIALS_PATH', default='')


# ---------------------------------------------------------------------------
# Upload limits
# ---------------------------------------------------------------------------
# Reels are videos, so anything over this threshold is streamed to a temp file
# on disk instead of being buffered in RAM. nginx enforces the hard ceiling
# (client_max_body_size); this only controls where Django buffers the bytes.
FILE_UPLOAD_MAX_MEMORY_SIZE = env.int('DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE', default=5 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', default=5 * 1024 * 1024)
DATA_UPLOAD_MAX_NUMBER_FILES = env.int('DJANGO_DATA_UPLOAD_MAX_NUMBER_FILES', default=100)


# ---------------------------------------------------------------------------
# Production security
# ---------------------------------------------------------------------------
# Everything below is inert while DEBUG=True, so local development is
# unaffected. On the server DEBUG=False and these all switch on.
if not DEBUG:
    # nginx terminates TLS and forwards plain HTTP to gunicorn/daphne. Without
    # this header Django would think every request arrived over HTTP and would
    # redirect forever once SECURE_SSL_REDIRECT is on.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

    # Turn these on only AFTER the TLS certificate is installed, otherwise the
    # site becomes unreachable over plain HTTP during first setup.
    SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=False)
    SESSION_COOKIE_SECURE = env.bool('DJANGO_SECURE_COOKIES', default=False)
    CSRF_COOKIE_SECURE = env.bool('DJANGO_SECURE_COOKIES', default=False)

    # HSTS tells browsers to refuse plain HTTP to this domain for N seconds.
    # Start at 0, raise to 3600 once HTTPS is confirmed working, then to
    # 31536000 (one year). A wrong value here is painful to undo.
    SECURE_HSTS_SECONDS = env.int('DJANGO_SECURE_HSTS_SECONDS', default=0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
    SECURE_HSTS_PRELOAD = env.bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)

    SESSION_COOKIE_HTTPONLY = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# Everything goes to stdout/stderr. Do not log to a file inside a container:
# the file disappears with the container and nothing rotates it. `docker
# compose logs` and the json-file driver's rotation handle it instead.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': env('DJANGO_LOG_LEVEL', default='INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
