# Generated by Django 6.0.5 on 2026-05-11 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('variant', models.CharField(max_length=255)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified', 'Certified Pre-owned')], max_length=20)),
                ('mileage_km', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('cng', 'CNG')], max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT')], max_length=20)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('negotiable', models.BooleanField(default=False)),
                ('listing_duration', models.IntegerField(choices=[(30, '30 Days'), (60, '60 Days'), (90, '90 Days')])),
                ('location', models.CharField(max_length=255)),
                ('engine_type', models.CharField(max_length=100)),
                ('displacement', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('torque', models.CharField(max_length=100)),
                ('fuel_tank', models.CharField(max_length=100)),
                ('doors', models.PositiveIntegerField()),
                ('seating', models.PositiveIntegerField()),
                ('weight', models.CharField(max_length=100)),
                ('airbags', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('stability_control', models.BooleanField(default=False)),
                ('parking_sensors', models.BooleanField(default=False)),
                ('camera', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('infotainment', models.BooleanField(default=False)),
                ('audio', models.BooleanField(default=False)),
                ('upholstery', models.CharField(max_length=100)),
                ('windows', models.CharField(max_length=100)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerVehicleReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='reels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
                ('background_music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.music')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='vehicles.vehicle')),
            ],
        ),
    ]
