# Generated by Django 6.0.5 on 2026-05-20 22:19

import vehicles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealervehiclereel',
            name='video_file',
            field=models.FileField(upload_to='reels/', validators=[vehicles.validators.validate_video_duration]),
        ),
    ]
