# Generated by Django 6.0.5 on 2026-05-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_dealervehiclereel_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealervehiclereel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
