# Generated by Django 6.0.5 on 2026-05-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_like_savedreel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealervehiclereel',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
