# Generated by Django 6.0.5 on 2026-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_reelview'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
