# Generated by Django 6.0.5 on 2026-07-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicleinquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('crossover', 'Crossover'), ('pickup', 'Pickup'), ('coupe', 'Coupe'), ('van', 'Van')], max_length=20),
        ),
    ]
