# Generated by Django 6.0.5 on 2026-09-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_aivideogeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealervehiclereel',
            name='ai_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='vehicles.aivideogeneration'),
        ),
        migrations.AddField(
            model_name='dealervehiclereel',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
